language: php
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

branches:
  only:
    - master

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - DB=mysql

before_install:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update
  - travis_retry composer global require hirak/prestissimo

install:
  - travis_retry composer install --prefer-dist --no-interaction --ignore-platform-reqs

script:
  - vendor/bin/phpunit
